### ISSUE TITLE
Publish a recent version to NPM

### ISSUE THREAD

**Issue by depoulo** [webpack-contrib/multi-loader#12]
Quoting https://www.npmjs.com/package/multi-loader

> version 0.1.0
> last publish 4 years ago

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.

**Comment by depoulo** [comment]
It has begun. The machines have taken over...
