### ISSUE TITLE
Webpack v2 Example

### ISSUE THREAD

**Issue by kochis** [webpack-contrib/multi-loader#9]
Is it possible to use this with webpack v2? If so, would it be possible to add an example using the new loader syntax (with object based config, instead of query params)?

Thanks!

**Comment by delsvr** [comment]
You can use combine-loaders (https://github.com/jsdf/webpack-combine-loaders) to stringify your loader configuration, and that will mostly get you there; e.g.

```javascript
{
   test: \/.scss$\/,
   use: multi-loader(combineLoaders({ ... }), ... )
}
```

But I'm also wondering how to ExtractTextPlugin working with multi-loader. Notably, the example [here](https://github.com/webpack-contrib/sass-loader/issues/205#issuecomment-256716899) no longer seems to work in webpack 2/3; there is no extracted file after compilation. Anyone have any ideas here?

**Comment by thasmo** [comment]
Thanks a lot for discussing this topic here, saved my day! I'd love to see support for webpack 3 and 4 tho too!

**Comment by shellscape** [comment]
Webpack 2 is realllly old now, and it looks like there's a solution found. The next major version will be webpack v4+.
